export const AMAZON_S3_SERVICE_KEY = Symbol('AMAZON_S3_SERVICE_KEY');
export const AMAZON_S3_OPTION_KEY = Symbol('AMAZON_S3_OPTION_KEY');
export const AMAZON_S3_BUCKET_KEY = Symbol('AMAZON_S3_BUCKET_KEY');
export const AMAZON_CLOUDFRONT_KEY = Symbol('AMAZON_CLOUDFRONT_KEY');
export const AWS_DISTRIBUTIONS_KEY = Symbol('AWS_DISTRIBUTIONS_KEY');
export const AWS_IMAGE_OPTIMIZE_SERVICE_KEY = Symbol(
  'AWS_IMAGE_OPTIMIZE_SERVICE_KEY',
);
export const AWS_CLOUDFRONT_DISTRIBUTION_DOMAIN_NAME = Symbol(
  'AWS_CLOUDFRONT_DISTRIBUTION_DOMAIN_NAME',
);
