export const TRANSACTION_MANAGER_SERVICE = Symbol(
  'TRANSACTION_MANAGER_SERVICE',
);
export const PAGINATION_SERVICE = Symbol('PAGINATION_SERVICE');
export const TRANSFORM_RESULT_SERVICE = Symbol('TRANSFORM_RESULT_SERVICE');

export const LOCALIZATION_SERVICE = Symbol('LOCALIZATION_SERVICE');
