export const DEPARTMENT_APPLICATION_SERVICE = Symbol(
  'DEPARTMENT_APPLICATION_SERVICE',
);
export const WRITE_DEPARTMENT_REPOSITORY = Symbol(
  'WRITE_DEPARTMENT_REPOSITORY',
);
export const READ_DEPARTMENT_REPOSITORY = Symbol('READ_DEPARTMENT_REPOSITORY');


// documentType
export const DOCUMENT_TYPE_APPLICATION_SERVICE = Symbol(
  'DOCUMENT_TYPE_APPLICATION_SERVICE',
);
export const WRITE_DOCUMENT_TYPE_REPOSITORY = Symbol(
  'WRITE_DOCUMENT_TYPE_REPOSITORY',
);
export const READ_DOCUMENT_TYPE_REPOSITORY = Symbol('READ_DOCUMENT_TYPE_REPOSITORY');


// user
export const USER_APPLICATION_SERVICE = Symbol(
  'USER_APPLICATION_SERVICE',
);
export const WRITE_USER_REPOSITORY = Symbol(
  'WRITE_USER_REPOSITORY',
);
export const READ_USER_REPOSITORY = Symbol('READ_USER_REPOSITORY');


// role
export const ROLE_APPLICATION_SERVICE = Symbol(
  'ROLE_APPLICATION_SERVICE',
);
export const WRITE_ROLE_REPOSITORY = Symbol(
  'WRITE_ROLE_REPOSITORY',
);
export const READ_ROLE_REPOSITORY = Symbol('READ_ROLE_REPOSITORY');


// permission
export const PERMISSION_APPLICATION_SERVICE = Symbol(
  'PERMISSION_APPLICATION_SERVICE',
);
export const WRITE_PERMISSION_REPOSITORY = Symbol(
  'WRITE_PERMISSION_REPOSITORY',
);
export const READ_PERMISSION_REPOSITORY = Symbol('READ_PERMISSION_REPOSITORY');


// unit
export const UNIT_APPLICATION_SERVICE = Symbol(
  'UNIT_APPLICATION_SERVICE',
);
export const WRITE_UNIT_REPOSITORY = Symbol(
  'WRITE_UNIT_REPOSITORY',
);
export const READ_UNIT_REPOSITORY = Symbol('READ_UNIT_REPOSITORY');


// department user
export const DEPARTMENT_USER_APPLICATION_SERVICE = Symbol(
  'DEPARTMENT_USER_APPLICATION_SERVICE',
);
export const WRITE_DEPARTMENT_USER_REPOSITORY = Symbol(
  'WRITE_DEPARTMENT_USER_REPOSITORY',
);
export const READ_DEPARTMENT_USER_REPOSITORY = Symbol('READ_DEPARTMENT_USER_REPOSITORY');