/** Limit Code */
export const LENGTH_DEPARTMENT_CODE = 6;
export const LENGTH_DOCUMENT_CODE = 6;

export const DEPARTMENT_APPLICATION_SERVICE = Symbol(
  'DEPARTMENT_APPLICATION_SERVICE',
);
export const WRITE_DEPARTMENT_REPOSITORY = Symbol(
  'WRITE_DEPARTMENT_REPOSITORY',
);
export const READ_DEPARTMENT_REPOSITORY = Symbol('READ_DEPARTMENT_REPOSITORY');

// documentType
export const DOCUMENT_TYPE_APPLICATION_SERVICE = Symbol(
  'DOCUMENT_TYPE_APPLICATION_SERVICE',
);
export const WRITE_DOCUMENT_TYPE_REPOSITORY = Symbol(
  'WRITE_DOCUMENT_TYPE_REPOSITORY',
);
export const READ_DOCUMENT_TYPE_REPOSITORY = Symbol(
  'READ_DOCUMENT_TYPE_REPOSITORY',
);

// user
export const USER_APPLICATION_SERVICE = Symbol('USER_APPLICATION_SERVICE');
export const WRITE_USER_REPOSITORY = Symbol('WRITE_USER_REPOSITORY');
export const READ_USER_REPOSITORY = Symbol('READ_USER_REPOSITORY');

// role
export const ROLE_APPLICATION_SERVICE = Symbol('ROLE_APPLICATION_SERVICE');
export const WRITE_ROLE_REPOSITORY = Symbol('WRITE_ROLE_REPOSITORY');
export const READ_ROLE_REPOSITORY = Symbol('READ_ROLE_REPOSITORY');

// permission
export const PERMISSION_APPLICATION_SERVICE = Symbol(
  'PERMISSION_APPLICATION_SERVICE',
);
export const WRITE_PERMISSION_REPOSITORY = Symbol(
  'WRITE_PERMISSION_REPOSITORY',
);
export const READ_PERMISSION_REPOSITORY = Symbol('READ_PERMISSION_REPOSITORY');

// unit
export const UNIT_APPLICATION_SERVICE = Symbol('UNIT_APPLICATION_SERVICE');
export const WRITE_UNIT_REPOSITORY = Symbol('WRITE_UNIT_REPOSITORY');
export const READ_UNIT_REPOSITORY = Symbol('READ_UNIT_REPOSITORY');

// department user
export const DEPARTMENT_USER_APPLICATION_SERVICE = Symbol(
  'DEPARTMENT_USER_APPLICATION_SERVICE',
);
export const WRITE_DEPARTMENT_USER_REPOSITORY = Symbol(
  'WRITE_DEPARTMENT_USER_REPOSITORY',
);
export const READ_DEPARTMENT_USER_REPOSITORY = Symbol(
  'READ_DEPARTMENT_USER_REPOSITORY',
);

// position
export const POSITION_APPLICATION_SERVICE = Symbol(
  'POSITION_APPLICATION_SERVICE',
);
export const WRITE_POSITION_REPOSITORY = Symbol('WRITE_POSITION_REPOSITORY');
export const READ_POSITION_REPOSITORY = Symbol('READ_POSITION_REPOSITORY');

// category
export const CATEGORY_APPLICATION_SERVICE = Symbol(
  'CATEGORY_APPLICATION_SERVICE',
);
export const WRITE_CATEGORY_REPOSITORY = Symbol('WRITE_CATEGORY_REPOSITORY');
export const READ_CATEGORY_REPOSITORY = Symbol('READ_CATEGORY_REPOSITORY');

export const USER_PROFILE_IMAGE_FOLDER = 'department_signature';

// department approver
export const DEPARTMENT_APPROVER_APPLICATION_SERVICE = Symbol(
  'DEPARTMENT_APPROVER_APPLICATION_SERVICE',
);
export const WRITE_DEPARTMENT_APPROVER_REPOSITORY = Symbol(
  'WRITE_DEPARTMENT_APPROVER_REPOSITORY',
);
export const READ_DEPARTMENT_APPROVER_REPOSITORY = Symbol(
  'READ_DEPARTMENT_APPROVER_REPOSITORY',
);

// currency
export const CURRENCY_APPLICATION_SERVICE = Symbol(
  'CURRENCY_APPLICATION_SERVICE',
);
export const WRITE_CURRENCY_REPOSITORY = Symbol('WRITE_CURRENCY_REPOSITORY');
export const READ_CURRENCY_REPOSITORY = Symbol('READ_CURRENCY_REPOSITORY');

// vendor
export const VENDOR_APPLICATION_SERVICE = Symbol('VENDOR_APPLICATION_SERVICE');
export const WRITE_VENDOR_REPOSITORY = Symbol('WRITE_VENDOR_REPOSITORY');
export const READ_VENDOR_REPOSITORY = Symbol('READ_VENDOR_REPOSITORY');

// vendor bank account
export const VENDOR_BANK_ACCOUNT_APPLICATION_SERVICE = Symbol(
  'VENDOR_BANK_ACCOUNT_APPLICATION_SERVICE',
);
export const WRITE_VENDOR_BANK_ACCOUNT_REPOSITORY = Symbol(
  'WRITE_VENDOR_BANK_ACCOUNT_REPOSITORY',
);
export const READ_VENDOR_BANK_ACCOUNT_REPOSITORY = Symbol(
  'READ_VENDOR_BANK_ACCOUNT_REPOSITORY',
);

// budget approval rule
export const BUDGET_APPROVAL_RULE_APPLICATION_SERVICE = Symbol(
  'BUDGET_APPROVAL_RULE_APPLICATION_SERVICE',
);
export const WRITE_BUDGET_APPROVAL_RULE_REPOSITORY = Symbol(
  'WRITE_BUDGET_APPROVAL_RULE_REPOSITORY',
);
export const READ_BUDGET_APPROVAL_RULE_REPOSITORY = Symbol(
  'READ_BUDGET_APPROVAL_RULE_REPOSITORY',
);

// approval workflow
export const APPROVAL_WORKFLOW_APPLICATION_SERVICE = Symbol(
  'APPROVAL_WORKFLOW_APPLICATION_SERVICE',
);
export const WRITE_APPROVAL_WORKFLOW_REPOSITORY = Symbol(
  'WRITE_APPROVAL_WORKFLOW_REPOSITORY',
);
export const READ_APPROVAL_WORKFLOW_REPOSITORY = Symbol(
  'READ_APPROVAL_WORKFLOW_REPOSITORY',
);

// budget account
export const BUDGET_ACCOUNT_APPLICATION_SERVICE = Symbol(
  'BUDGET_ACCOUNT_APPLICATION_SERVICE',
);
export const WRITE_BUDGET_ACCOUNT_REPOSITORY = Symbol(
  'WRITE_BUDGET_ACCOUNT_REPOSITORY',
);
export const READ_BUDGET_ACCOUNT_REPOSITORY = Symbol(
  'READ_BUDGET_ACCOUNT_REPOSITORY',
);

// budget item
export const BUDGET_ITEM_APPLICATION_SERVICE = Symbol(
  'BUDGET_ITEM_APPLICATION_SERVICE',
);
export const WRITE_BUDGET_ITEM_REPOSITORY = Symbol(
  'WRITE_BUDGET_ITEM_REPOSITORY',
);
export const READ_BUDGET_ITEM_REPOSITORY = Symbol(
  'READ_BUDGET_ITEM_REPOSITORY',
);

// budget item detail
export const BUDGET_ITEM_DETAIL_APPLICATION_SERVICE = Symbol(
  'BUDGET_ITEM_DETAIL_APPLICATION_SERVICE',
);
export const WRITE_BUDGET_ITEM_DETAIL_REPOSITORY = Symbol(
  'WRITE_BUDGET_ITEM_DETAIL_REPOSITORY',
);
export const READ_BUDGET_ITEM_DETAIL_REPOSITORY = Symbol(
  'READ_BUDGET_ITEM_DETAIL_REPOSITORY',
);

// province
export const PROVINCE_APPLICATION_SERVICE = Symbol(
  'PROVINCE_APPLICATION_SERVICE',
);
export const WRITE_PROVINCE_REPOSITORY = Symbol('WRITE_PROVINCE_REPOSITORY');
export const READ_PROVINCE_REPOSITORY = Symbol('READ_PROVINCE_REPOSITORY');

// document
export const DOCUMENT_APPLICATION_SERVICE = Symbol(
  'DOCUMENT_APPLICATION_SERVICE',
);
export const WRITE_DOCUMENT_REPOSITORY = Symbol('WRITE_DOCUMENT_REPOSITORY');
export const READ_DOCUMENT_REPOSITORY = Symbol('READ_DOCUMENT_REPOSITORY');

// purchase request
export const PURCHASE_REQUEST_APPLICATION_SERVICE = Symbol(
  'PURCHASE_REQUEST_APPLICATION_SERVICE',
);
export const WRITE_PURCHASE_REQUEST_REPOSITORY = Symbol(
  'WRITE_PURCHASE_REQUEST_REPOSITORY',
);
export const READ_PURCHASE_REQUEST_REPOSITORY = Symbol(
  'READ_PURCHASE_REQUEST_REPOSITORY',
);

// purchase request item
export const PURCHASE_REQUEST_ITEM_APPLICATION_SERVICE = Symbol(
  'PURCHASE_REQUEST_ITEM_APPLICATION_SERVICE',
);
export const WRITE_PURCHASE_REQUEST_ITEM_REPOSITORY = Symbol(
  'WRITE_PURCHASE_REQUEST_ITEM_REPOSITORY',
);
export const READ_PURCHASE_REQUEST_ITEM_REPOSITORY = Symbol(
  'READ_PURCHASE_REQUEST_ITEM_REPOSITORY',
);
