export const REPORT_PURCHASE_REQUEST_APPLICATION_SERVICE = Symbol(
  'REPORT_PURCHASE_REQUEST_APPLICATION_SERVICE',
);
export const REPORT_PURCHASE_REQUEST_REPOSITORY = Symbol(
  'REPORT_PURCHASE_REQUEST_REPOSITORY',
);

export const REPORT_PURCHASE_ORDER_APPLICATION_SERVICE = Symbol(
  'REPORT_PURCHASE_ORDER_APPLICATION_SERVICE',
);
export const REPORT_PURCHASE_ORDER_REPOSITORY = Symbol(
  'REPORT_PURCHASE_ORDER_REPOSITORY',
);

export const REPORT_RECEIPT_APPLICATION_SERVICE = Symbol(
  'REPORT_RECEIPT_APPLICATION_SERVICE',
);
export const REPORT_RECEIPT_REPOSITORY = Symbol('REPORT_RECEIPT_REPOSITORY');
